#!/usr/bin/env bash
# Seed the live registry: real prior work, real open problems, no fictional
# activity. Contrast with ./demo.sh, which replays a scripted walkthrough
# with fictional participants to demonstrate every mechanism.
#
# Everything below is sourced and dated. Statistics were read from the cited
# pages on the given dates; nothing here is generated by the registry itself.
set -euo pipefail
cd "$(dirname "$0")"

# This script builds a local dataset; never publish its events to a
# configured remote registry, and keep its keys out of the user's own
# key directory.
export RAZOR_REMOTE=
export RAZOR_KEYS_DIR="$PWD/registry/data/keys"
RAZOR=./target/release/razor
step() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }

if [ ! -x "$RAZOR" ]; then
  step "Build the registry CLI"
  cargo build --release -p razor-registry 2>&1 | tail -1
fi

step "Fresh registry"
# Regenerate everything under registry/data except keys/: signing keys are
# identities, not dataset, and are never deleted by any script.
find registry/data -mindepth 1 -maxdepth 1 ! -name keys ! -name statements -exec rm -rf {} + 2>/dev/null || true
rm -rf site/data.json

# ─────────────────────────────────────────────────────────────────────
step "Recognize prior corpora - work that is already done"
# ─────────────────────────────────────────────────────────────────────
# Mathlib is not re-verified or restated here. Recognizing it as a corpus
# means: the registry treats its contents as solved, and a hole whose
# statement already exists in Mathlib is closed by citing it.

$RAZOR corpus --id mathlib \
  --name "Mathlib" \
  --url "https://leanprover-community.github.io/" \
  --source "https://leanprover-community.github.io/mathlib_stats.html" \
  --as-of "2026-07-02" \
  --stat "definitions=133,477" \
  --stat "theorems=281,364" \
  --stat "contributors=772" \
  --note "The Lean community's mathematical library. Every declaration in it is already machine-checked by the same kernel this registry uses, so the registry treats all of it as done. New holes should state what Mathlib does not yet contain; a hole later found to duplicate a Mathlib result is closed by citation, not re-proved."

$RAZOR corpus --id formal-conjectures \
  --name "formal-conjectures (Google DeepMind)" \
  --url "https://github.com/google-deepmind/formal-conjectures" \
  --source "https://github.com/google-deepmind/formal-conjectures/milestone/1" \
  --as-of "2026-07-02" \
  --stat "Erdos problems on erdosproblems.com=1,100+" \
  --stat "of those still open=~680" \
  --stat "open problems in the formalization milestone=693" \
  --stat "statements already formalized in Lean=~240" \
  --stat "solutions formalized in Lean=17" \
  --note "A collection of conjecture statements formalized in Lean, centered on the problems of Paul Erdos as catalogued at erdosproblems.com. This is the closest existing thing to a frontier registry: precise Lean statements of problems nobody has solved. Holes here should link to the corresponding formal-conjectures entry rather than restate it."

$RAZOR corpus --id physlib \
  --name "Physlib (formerly PhysLean / HepLean)" \
  --url "https://physlib.io/" \
  --source "https://physlib.io/" \
  --as-of "2026-07-02" \
  --stat "arXiv reference=2405.08863" \
  --note "An open-source community project to digitalize results from physics into Lean 4 - definitions, theorems, and calculations, with Wick's theorem as a documented example. Physics formalization is far earlier-stage than mathematics: most of the subject has no formal counterpart yet, which makes it the widest open frontier reachable from Lean today."

# ─────────────────────────────────────────────────────────────────────
step "Real open problems, entered as proposals"
# ─────────────────────────────────────────────────────────────────────
# A proposal is the funnel's first stage: a problem in plain language, not
# yet a machine-checkable statement. These are real problems the Lean
# community is working toward or has not started; formalizing each one into
# a pinned statement is itself the first open task.

$RAZOR propose --id PRP-001 --author "registry" \
  --title "Fermat's Last Theorem, formalized" \
  --body "The FLT project led by Kevin Buzzard at Imperial College London is formalizing Fermat's Last Theorem in Lean, with the interim goal of reducing it to results that were known to experts by 1989. It is the largest single formalization effort in mathematics and is not in Mathlib. Reference: https://github.com/ImperialCollegeLondon/FLT. Holes under this proposal should track the project's stated open sub-goals rather than the full theorem."

$RAZOR propose --id PRP-002 --author "registry" \
  --title "Erdos-Straus conjecture" \
  --body "For every integer n >= 2, the fraction 4/n can be written as 1/x + 1/y + 1/z with x, y, z positive integers. Open since 1948. A Lean statement is straightforward to pin, which makes this a good first hole to formalize from this list. See erdosproblems.com and the formal-conjectures corpus for the statement conventions to follow."

$RAZOR propose --id PRP-003 --author "registry" \
  --title "Erdos-Turan conjecture on additive bases" \
  --body "If A is a set of natural numbers such that every sufficiently large integer is a sum of two elements of A, then the number of ways to write n as such a sum cannot stay bounded. Open since 1941. Like PRP-002, the statement is elementary enough to formalize directly against core Lean or Mathlib."

$RAZOR propose --id PRP-004 --author "registry" \
  --title "Noether's theorem for classical field theories" \
  --body "Physics frontier. Physlib (the corpus above) is digitalizing physics into Lean, and most of classical mechanics and field theory has no formal counterpart. A machine-checked derivation of Noether's theorem - every differentiable symmetry of the action corresponds to a conservation law - would be a foundational entry that many later results depend on. First task: pin what 'action', 'symmetry', and 'conserved current' mean formally."

$RAZOR propose --id PRP-005 --author "registry" \
  --title "The Ito integral for Mathlib" \
  --body "Missing Mathlib library. Mathlib's probability theory does not yet reach stochastic calculus: the Ito integral, Ito's formula, and stochastic differential equations have no usable formal development. This blocks formal work on mathematical finance, filtering, and stochastic PDEs. The hole structure should follow the decomposition the informal theory already has: predictable processes, the isometry, the integral, then the formula."

$RAZOR propose --id PRP-006 --author "registry" \
  --title "The heat equation and its smoothing estimates" \
  --body "Missing Mathlib library. Mathlib has strong foundations in measure theory and functional analysis but very little partial differential equation theory. The heat equation on R^n - existence of solutions via the heat kernel, uniqueness under growth conditions, smoothing - is the standard first target, and its absence blocks most of formal mathematical physics."

# ─────────────────────────────────────────────────────────────────────
step "The 1000+ theorems frontier, ingested"
# ─────────────────────────────────────────────────────────────────────
# The 1000+ project (successor of Freek Wiedijk's 'Formalizing 100
# Theorems') catalogues notable theorems and which proof assistants have
# formalized each one. Every entry with no Lean proof enters here as its
# own proposal - a real, sourced work queue, not an invented one. The
# snapshot is committed and dated; refresh it with
#   uv run ingest/fetch_thousand_plus.py --as-of <date>

$RAZOR corpus --id thousand-plus \
  --name "1000+ theorems list" \
  --url "https://1000-plus.github.io/" \
  --source "https://github.com/1000-plus/1000-plus.github.io" \
  --as-of "2026-07-03" \
  --stat "theorems catalogued=1,199" \
  --stat "with Lean proofs=224" \
  --stat "without Lean formalization=975" \
  --note "A community catalogue of notable theorems and their formalization status across proof assistants, maintained as the successor of Freek Wiedijk's 'Formalizing 100 Theorems'. The 975 entries without a Lean formalization are ingested below as proposals: each needs a pinned statement, written with Mathlib's definitions, before it is a solvable hole, and that formalization work is itself attributed on this log."

$RAZOR propose-batch --file ingest/data/thousand-plus.jsonl --author "registry"

# ─────────────────────────────────────────────────────────────────────
step "First real formalization: Erdos-Straus, pinned as a hole"
# ─────────────────────────────────────────────────────────────────────
# PRP-002 is elementary enough to state formally today. Two candidate
# statements are registered: a core-Lean form with denominators cleared
# (compile-checked in lean/Razor/Frontier/ErdosStraus.lean) and a
# form over the rationals using Mathlib's definitions (lean-mathlib/). Proving the
# two equivalent is itself an open convergence task, so for now each is a
# clump of one and neither is dominant - the registry says exactly how much
# trust the statement has earned, which today is: certificates only.

$RAZOR formalize --id STM-ES-CORE --proposal PRP-002 --author "registry" \
  --decl Razor.Frontier.ErdosStraus \
  --gloss "for every n >= 2 there are positive x, y, z with 4xyz = n(yz + xz + xy) - the fraction form 4/n = 1/x + 1/y + 1/z with denominators cleared, so it needs no rational-number library" \
  --notes "core Lean, no dependencies; see lean/Razor/Frontier/ErdosStraus.lean"

$RAZOR formalize --id STM-ES-RAT --proposal PRP-002 --author "registry" \
  --decl RazorMathlib.ErdosStrausRat \
  --gloss "for every n >= 2 there are positive integers x, y, z with 4/n = 1/x + 1/y + 1/z, stated directly over Mathlib's rationals" \
  --notes "Mathlib environment (lean-mathlib/); fetch it with ./mathlib-env.sh. Proving this equivalent to STM-ES-CORE is an open convergence task."

$RAZOR certify --statement STM-ES-CORE --kind instance-check \
  --decl Razor.Frontier.erdosStraus_case_two \
  --notes "n = 2 case witnessed by 1, 2, 2 (4/2 = 1/1 + 1/2 + 1/2)"
$RAZOR certify --statement STM-ES-CORE --kind instance-check \
  --decl Razor.Frontier.erdosStraus_case_three \
  --notes "n = 3 case witnessed by 1, 4, 12 (4/3 = 1/1 + 1/4 + 1/12)"
$RAZOR certify --statement STM-ES-CORE --kind non-vacuity \
  --decl Razor.Frontier.erdosStraus_nonvacuous \
  --notes "the hypothesis 2 <= n is satisfiable"

$RAZOR hole --id ES-001 --proposal PRP-002 --statement STM-ES-CORE \
  --title "Erdos-Straus (naturals, denominators cleared)" \
  --lean-type "Razor.Frontier.ErdosStraus"

$RAZOR hole --id ES-002 --proposal PRP-002 --statement STM-ES-RAT --env mathlib \
  --title "Erdos-Straus (rationals, in the Mathlib environment)" \
  --lean-type "RazorMathlib.ErdosStrausRat"

# A real challenge window: both readings above are one author's (the
# registry's), so the proposal has no independent convergence evidence at
# all. The window invites sealed readings - statements committed as hashes
# before any is revealed - because two readings sealed before one another's
# reveals are *provably* written blind, and equivalence between them is the
# strongest fidelity evidence a statement can earn. Dates are absolute so
# replaying this seed reproduces the same log content.
$RAZOR round --id RND-ES-1 --proposal PRP-002 --author "registry" \
  --closes-at 1786665600 --reveal-by 1787270400 \
  --note "seal your own Lean reading of Erdos-Straus by 2026-08-14, reveal by 2026-08-21. Both existing statements are the registry's own; a sealed reading that bridges to either is the first independent convergence evidence this proposal can get."

# ─────────────────────────────────────────────────────────────────────
step "The Mathlib environment is the default for new holes"
# ─────────────────────────────────────────────────────────────────────
# A proof is worth most where it can be built on, and for mathematics that
# place is Mathlib. New holes should be stated using Mathlib's definitions
# (razor hole --env mathlib); the core-Lean environment stays for
# statements that deliberately avoid all dependencies. Where Mathlib
# already names the Prop - as it does for Fermat's Last Theorem - the hole
# pins Mathlib's own name, so a proof accepted by Mathlib closes the hole
# verbatim: no restatement, no translation risk.

$RAZOR formalize --id STM-ET-MATHLIB --proposal PRP-003 --author "registry" \
  --decl RazorMathlib.ErdosTuranAdditiveBasis \
  --gloss "if every sufficiently large natural number is a sum of two elements of A, the number of representations n = a + b with a, b in A is unbounded; ordered pairs are counted, which changes nothing about boundedness" \
  --notes "Mathlib environment (lean-mathlib/RazorMathlib/Statements.lean), stated with Set.ncard and Filter.atTop"

$RAZOR hole --id ET-001 --proposal PRP-003 --statement STM-ET-MATHLIB --env mathlib \
  --title "Erdos-Turan on additive bases (in the Mathlib environment)" \
  --lean-type "RazorMathlib.ErdosTuranAdditiveBasis"

# ─────────────────────────────────────────────────────────────────────
step "Fermat's Last Theorem: one statement, two competing splits"
# ─────────────────────────────────────────────────────────────────────
# PRP-001 tracks the FLT project. The full theorem is statable in core Lean
# today (lean/Razor/Frontier/FLT.lean), and its classical reduction makes it
# the clearest real example of the split mechanism: a split reduces a parent
# hole to child holes plus a glue hole, and the glue - "the children jointly
# imply the parent" - is proven and kernel-checked below while every child
# is still open. Both glue proofs are real proofs, checked by the kernel
# during this seed; the children are genuinely open and stay that way.

$RAZOR formalize --id STM-FLT-CORE --proposal PRP-001 --author "registry" \
  --decl Razor.Frontier.FLT \
  --gloss "for every exponent n >= 3 there are no positive natural numbers x, y, z with x^n + y^n = z^n" \
  --notes "core Lean, no dependencies; see lean/Razor/Frontier/FLT.lean. The FLT project states the theorem using Mathlib's definitions; proving the two forms equivalent is an open convergence task."

$RAZOR certify --statement STM-FLT-CORE --kind instance-check \
  --decl Razor.Frontier.flt_instance_check \
  --notes "the near-miss 3^3 + 4^3 = 91 is rejected at exponent 3 (not 125)"

$RAZOR hole --id FLT-000 --proposal PRP-001 --statement STM-FLT-CORE \
  --title "Fermat's Last Theorem (naturals, core Lean)" \
  --lean-type "Razor.Frontier.FLT"

# Mathlib states FLT itself, so the flagship hole pins Mathlib's own Prop:
# whatever proof the FLT project lands in Mathlib closes FLT-M verbatim.
$RAZOR formalize --id STM-FLT-MATHLIB --proposal PRP-001 --author "registry" \
  --decl FermatLastTheorem \
  --gloss "Mathlib's own statement: for every n >= 3 there are no positive naturals x, y, z with x^n + y^n = z^n" \
  --notes "the Prop is defined by Mathlib itself (FermatLastTheorem, in Mathlib.NumberTheory.FLT.Basic) - the exact statement the Imperial FLT project is proving. Proving it equivalent to STM-FLT-CORE is an open convergence task."

$RAZOR hole --id FLT-M --proposal PRP-001 --statement STM-FLT-MATHLIB --env mathlib \
  --title "Fermat's Last Theorem (Mathlib's own statement)" \
  --lean-type "FermatLastTheorem"

# The children of both splits. FLT-4 is shared between them - a hole can
# serve in any number of splits.
$RAZOR hole --id FLT-3 --proposal PRP-001 \
  --title "FLT for exponent 3 (Euler's case)" \
  --lean-type "Razor.Frontier.FLTFor 3"
$RAZOR hole --id FLT-4 --proposal PRP-001 \
  --title "FLT for exponent 4 (Fermat's own case)" \
  --lean-type "Razor.Frontier.FLTFor 4"
$RAZOR hole --id FLT-ODD --proposal PRP-001 \
  --title "FLT for every odd prime exponent" \
  --lean-type "Razor.Frontier.FLTOddPrimes"
$RAZOR hole --id FLT-P5 --proposal PRP-001 \
  --title "FLT for every prime exponent >= 5" \
  --lean-type "Razor.Frontier.FLTPrimesGE5"
$RAZOR hole --id FLT-RED --proposal PRP-001 \
  --title "every exponent >= 3 factors through 4 or an odd prime" \
  --lean-type "Razor.Frontier.ExponentReduction"
$RAZOR hole --id FLT-REDF --proposal PRP-001 \
  --title "every exponent >= 3 factors through 3, 4, or a prime >= 5" \
  --lean-type "Razor.Frontier.ExponentReductionFine"

# Split A: the classical reduction (exponent 4 + odd primes).
$RAZOR split --id SPL-FLT-A --parent FLT-000 --author "registry" \
  --child FLT-4 --child FLT-ODD --child FLT-RED \
  --note "the classical reduction: a counterexample at exponent n is one at a divisor of n that is 4 or an odd prime"
$RAZOR submit --id SUB-FLT-GA --hole SPL-FLT-A-glue --solver "registry" \
  --decl Razor.Frontier.fltSplitA_glue
$RAZOR verify --submission SUB-FLT-GA

# Split B: the same parent refactored to mirror the FLT project's actual
# plan. Their Wiles/Taylor-Wiles machinery needs p >= 5 (the Frey curve
# argument fails below that), and Mathlib already has n = 3 and n = 4 - so
# "every odd prime" was the wrong cut. Split A stays on the record: its
# glue is a true theorem, and refactoring means registering another split,
# never editing one.
$RAZOR split --id SPL-FLT-B --parent FLT-000 --author "registry" \
  --child FLT-3 --child FLT-4 --child FLT-P5 --child FLT-REDF \
  --note "the FLT project's own top-level plan (blueprint: reduction to n >= 5 and prime); n = 3 and n = 4 are already proven in Mathlib, so those children could close by convergence with Mathlib statements"
$RAZOR submit --id SUB-FLT-GB --hole SPL-FLT-B-glue --solver "registry" \
  --decl Razor.Frontier.fltSplitB_glue
$RAZOR verify --submission SUB-FLT-GB

$RAZOR curate --curator "registry" --target FLT-RED \
  --note "self-contained number theory, no imports needed - a genuinely provable first hole on this board"

# ─────────────────────────────────────────────────────────────────────
step "Export for the site"
# ─────────────────────────────────────────────────────────────────────
$RAZOR export --out site/data.json --dataset live
$RAZOR status
